services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.4
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr=internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy.*true'"]
      interval: 5s
      timeout: 10s
      retries: 20

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  producer:
    build: ./producer
    environment:
      KAFKA_BOOTSTRAP: redpanda:9092
      TOPIC: transactions
      RATE_PER_SEC: "25"
    depends_on:
      redpanda:
        condition: service_healthy

  detector:
    build: ./detector
    environment:
      KAFKA_BOOTSTRAP: redpanda:9092
      TRANSACTIONS_TOPIC: transactions
      ANOMALIES_TOPIC: anomalies
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redpanda:
        condition: service_healthy
      redis:
        condition: service_healthy

  dashboard:
    build: ./dashboard
    ports:
      - "8088:8088"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
